{% set name = "nix" %}
{% set version = "2.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://nixos.org/releases/nix/nix-{{ version }}/nix-{{ version }}.tar.xz
  sha256: 7ee681b69f05b525492d202c3bedcd9dee1960bb818f62690f6c4493b7c2aabc

build:
  number: 4
  skip: true  # [win]
  ignore_run_exports:
    - libxslt
    - libxml2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - openssl
    - brotli
    - bzip2
    - liblzma-devel
    - curl
    - sqlite
    - libboost-devel
    - editline
    - libxml2
    - libxslt
    - bison
    - flex
    - libseccomp  # [linux]
    - zlib
  run:
    - brotli
    - libcurl
    - curl
    - editline

test:
  commands:
    - nix --help

about:
  home: https://nixos.org/nix/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: The Purely Functional Package Manager
  description: |
    Nix is a powerful package manager for Linux and other Unix systems
    that makes package management reliable and reproducible. It provides
    atomic upgrades and rollbacks, side-by-side installation of multiple
    versions of a package, multi-user package management and easy setup
    of build environments.
  doc_url: https://nixos.org/nix/manual/
  dev_url: https://github.com/NixOS/nix

extra:
  recipe-maintainers:
    - scopatz
